require 'nn'
require 'gnuplot'
--[[
torch.manualSeed(0)
ii = torch.linspace(0, 1, 10)
print(ii)
m = nn.SoftMax()
oo = m:forward(ii)
go = torch.ones(10)
print(oo)
gi = m:backward(ii, go)
gnuplot.plot({'f(x)', ii, oo, '+-'}, {'df/dx', ii, go, '+-'})
gnuplot.grid(true)
]]--
torch.manualSeed(0)
x = torch.rand(4) -- 10 inputs
print("x:")
print(x)
mlp = nn.Sequential()
module = nn.Linear(4, 2)
mlp:add(module)
module.weight = torch.ones(2,4)
module.bias = torch.ones(2)
print("module.weight:")
print(module.weight)
print("module.bias:")
print(module.bias)
print("module:forward(x):")
print(module:forward(x))
print("dout:")
dout = 2*torch.ones(2)
print(dout)
print("module:backward")
print(module:backward(x,dout))
print("module.gradWeight:")
print(module.gradWeight)
print("module.gradBias:")
print(module.gradBias)